#pragma once

#define CUJ_ANONYMOUS_NAME_CAT(A, B) CUJ_ANONYMOUS_NAME_CAT_IMPL(A, B)
#define CUJ_ANONYMOUS_NAME_CAT_IMPL(A, B) A##B

#ifdef __COUNTER__
#define CUJ_ANONYMOUS_NAME(STR) CUJ_ANONYMOUS_NAME_CAT(STR, __COUNTER__)
#else
#define CUJ_ANONYMOUS_NAME(STR) CUJ_ANONYMOUS_NAME_CAT(STR, __LINE__)
#endif
